import type { Shipper } from '../src/lib/data'

type Seed = Omit<Shipper, 'demo' | 'verifiedAt' | 'createdAt'>
const S = (s: Seed) => s

/**
 * Additional fictional shippers so the directory has enough depth for search, filters and pagination.
 * All are `demo = true`; remove them once real forwarders are listed. Names, ratings and figures are invented.
 */
export const extraShippers: Seed[] = [
  S({ id: 'accra-parcel-co', name: 'Accra Parcel Co.', tagline: 'Boxes and barrels, door to door in Greater Accra', hq: 'Bronx, NY', founded: 2014, modes: ['ocean'], destinations: ['GH'], origins: ['New York, NY', 'Newark, NJ', 'Providence, RI'], cargo: ['barrels', 'boxes'], rating: 4.6, reviews: 221, verified: true, responseHours: 2, onTime: 93, services: ['Door pickup', 'Door delivery Accra', 'Barrel supply'], about: 'Started as a barrel-drop in the Bronx; now sails monthly to Tema with our own vans in Accra. Groupage only — no vehicles.', priceIndex: 1, plan: 'starter', initials: 'AP', hue: '#F59E0B' }),
  S({ id: 'lagos-lane-express', name: 'Lagos Lane Express', tagline: 'Fortnightly to Apapa with pre-clearance', hq: 'Houston, TX', founded: 2012, modes: ['ocean', 'air'], destinations: ['NG'], origins: ['Houston, TX', 'Dallas, TX', 'Atlanta, GA'], cargo: ['barrels', 'boxes', 'pallets', 'vehicle', 'container20', 'container40'], rating: 4.7, reviews: 264, verified: true, responseHours: 2, onTime: 94, services: ['Door pickup', 'Customs pre-clearance', 'Vehicle inspection', 'Insurance'], about: 'Texas-based Nigerian-owned forwarder. Pre-clearance paperwork starts before the vessel sails so cargo leaves Apapa within days.', priceIndex: 2, plan: 'enterprise', initials: 'LL', hue: '#34D399' }),
  S({ id: 'tema-tide', name: 'Tema Tide Shipping', tagline: 'Containers and RoRo into Tema every week', hq: 'Baltimore, MD', founded: 2009, modes: ['ocean'], destinations: ['GH', 'TG'], origins: ['Baltimore, MD', 'Philadelphia, PA', 'New York, NY'], cargo: ['vehicle', 'container20', 'container40', 'pallets'], rating: 4.8, reviews: 347, verified: true, responseHours: 1, onTime: 96, services: ['RoRo vehicles', 'FCL & LCL', 'Customs brokerage', 'Duty estimates'], about: 'Baltimore RoRo specialists. Weekly sailings; duty estimates within the hour so you know the landed cost before you book.', priceIndex: 2, plan: 'pro', initials: 'TT', hue: '#60A5FA' }),
  S({ id: 'harmattan-air', name: 'Harmattan Air Logistics', tagline: 'Daily uplift to Accra, Lagos and Abidjan', hq: 'Atlanta, GA', founded: 2017, modes: ['air'], destinations: ['GH', 'NG', 'CI', 'SN'], origins: ['Atlanta, GA', 'New York, NY', 'Chicago, IL', 'Los Angeles, CA'], cargo: ['boxes', 'pallets', 'commercial'], rating: 4.7, reviews: 158, verified: true, responseHours: 1, onTime: 95, services: ['Same-day pickup (Atlanta)', 'Temperature-controlled', 'Pharma certified', 'Airport-to-door'], about: 'IATA forwarder out of Hartsfield-Jackson. Best for urgent commercial and medical cargo — 2–4 day door delivery on most lanes.', priceIndex: 3, plan: 'pro', initials: 'HA', hue: '#A78BFA' }),
  S({ id: 'freetown-freight', name: 'Freetown Freight Line', tagline: 'Sierra Leone groupage from the UK & US', hq: 'London, UK', founded: 2011, modes: ['ocean'], destinations: ['SL', 'LR'], origins: ['London, UK', 'Manchester, UK', 'New York, NY'], cargo: ['barrels', 'boxes', 'pallets', 'vehicle'], rating: 4.5, reviews: 132, verified: true, responseHours: 4, onTime: 91, services: ['Door pickup (UK)', 'Door delivery Freetown', 'Vehicle shipping'], about: 'Monthly consolidations from Tilbury and Newark into Queen Elizabeth II Quay, with our own clearance team in Freetown.', priceIndex: 1, plan: 'starter', initials: 'FF', hue: '#FB7185' }),
  S({ id: 'cotonou-crossing', name: 'Cotonou Crossing', tagline: 'Benin, Togo and the Sahel via Lomé', hq: 'Paris, FR', founded: 2008, modes: ['ocean'], destinations: ['TG', 'CI'], origins: ['Paris, FR', 'Hamburg, DE', 'Rotterdam, NL'], cargo: ['vehicle', 'container20', 'container40', 'commercial'], rating: 4.6, reviews: 198, verified: true, responseHours: 3, onTime: 93, services: ['RoRo vehicles', 'FCL', 'Transit bonds to Burkina & Niger'], about: 'French forwarder specialising in transit cargo through Lomé to landlocked Sahel countries. Strong on used vehicles and machinery.', priceIndex: 2, plan: 'starter', initials: 'CC', hue: '#F472B6' }),
  S({ id: 'kumasi-kargo', name: 'Kumasi Kargo', tagline: 'Ashanti region door delivery, no middlemen', hq: 'Chicago, IL', founded: 2016, modes: ['ocean'], destinations: ['GH'], origins: ['Chicago, IL', 'Minneapolis, MN', 'Columbus, OH'], cargo: ['barrels', 'boxes', 'vehicle'], rating: 4.6, reviews: 174, verified: true, responseHours: 3, onTime: 92, services: ['Door pickup (Midwest)', 'Door delivery Kumasi', 'Barrel supply', 'WhatsApp tracking updates'], about: 'Midwest pickups every other week, trucked to Baltimore and sailed to Tema. Own delivery vans in Kumasi and Sunyani.', priceIndex: 1, plan: 'pro', initials: 'KK', hue: '#FBBF24' }),
  S({ id: 'abidjan-bridge', name: 'Abidjan Bridge Cargo', tagline: 'Côte d’Ivoire RoRo and reefer', hq: 'Le Havre, FR', founded: 2013, modes: ['ocean', 'air'], destinations: ['CI', 'SN'], origins: ['Paris, FR', 'Rotterdam, NL', 'Hamburg, DE'], cargo: ['vehicle', 'container20', 'container40', 'commercial', 'pallets'], rating: 4.7, reviews: 143, verified: true, responseHours: 2, onTime: 95, services: ['RoRo vehicles', 'Reefer containers', 'Customs brokerage Abidjan'], about: 'Weekly RoRo from Le Havre to Abidjan and refrigerated containers for food exporters. Bilingual team in Abidjan and Paris.', priceIndex: 2, plan: 'pro', initials: 'AB', hue: '#2DD4BF' }),
  S({ id: 'gulf-guinea-lines', name: 'Gulf of Guinea Lines', tagline: 'Multi-port FCL from Asia and the Gulf', hq: 'Dubai, AE', founded: 2007, modes: ['ocean'], destinations: ['NG', 'GH', 'CI', 'TG', 'SN'], origins: ['Dubai, AE', 'Shanghai, CN', 'Guangzhou, CN'], cargo: ['container20', 'container40', 'commercial'], rating: 4.5, reviews: 289, verified: true, responseHours: 6, onTime: 90, services: ['FCL', 'Project cargo', 'Letter-of-credit handling', 'Warehousing Jebel Ali'], about: 'Container line agent covering five West African ports from Jebel Ali and South China. Commercial importers only — no personal effects.', priceIndex: 2, plan: 'enterprise', initials: 'GG', hue: '#38BDF8' }),
  S({ id: 'diaspora-direct', name: 'Diaspora Direct', tagline: 'Barrels from anywhere in the US, one flat rate', hq: 'Los Angeles, CA', founded: 2018, modes: ['ocean'], destinations: ['GH', 'NG', 'LR', 'SL'], origins: ['Los Angeles, CA', 'Houston, TX', 'Atlanta, GA', 'New York, NY', 'Chicago, IL'], cargo: ['barrels', 'boxes'], rating: 4.4, reviews: 412, verified: true, responseHours: 5, onTime: 89, services: ['Nationwide pickup', 'Flat-rate barrels', 'Door delivery major cities'], about: 'Flat-rate barrel shipping with pickup anywhere in the continental US via partner trucks. Transit is slower but pricing is the simplest on the market.', priceIndex: 1, plan: 'starter', initials: 'DD', hue: '#F97316' }),
  S({ id: 'north-star-africa', name: 'North Star Africa Freight', tagline: 'Canada to West Africa, air and sea', hq: 'Toronto, CA', founded: 2010, modes: ['ocean', 'air'], destinations: ['GH', 'NG', 'SN'], origins: ['Toronto, CA', 'Montreal, CA'], cargo: ['barrels', 'boxes', 'pallets', 'vehicle', 'container20', 'commercial'], rating: 4.7, reviews: 203, verified: true, responseHours: 2, onTime: 94, services: ['Door pickup (GTA)', 'Vehicle export paperwork', 'Customs brokerage', 'Insurance'], about: 'Canada’s largest West Africa forwarder. Vehicles via Halifax RoRo, groupage monthly from Toronto, air from Pearson three times a week.', priceIndex: 2, plan: 'pro', initials: 'NS', hue: '#F87171' }),
  S({ id: 'manchester-maritime', name: 'Manchester Maritime', tagline: 'Northern England to Tema and Lagos', hq: 'Manchester, UK', founded: 2005, modes: ['ocean'], destinations: ['GH', 'NG'], origins: ['Manchester, UK', 'London, UK'], cargo: ['barrels', 'boxes', 'pallets', 'vehicle', 'container20', 'container40'], rating: 4.8, reviews: 356, verified: true, responseHours: 2, onTime: 96, services: ['Door pickup (UK)', 'Vehicle shipping', 'FCL & LCL', 'Customs brokerage'], about: 'Twenty years on the UK–West Africa trade. Our Trafford depot receives drop-offs six days a week.', priceIndex: 2, plan: 'pro', initials: 'MM', hue: '#C084FC' }),
  S({ id: 'dakar-dash', name: 'Dakar Dash Air', tagline: 'Perishables and pharma to Senegal in 48h', hq: 'New York, NY', founded: 2019, modes: ['air'], destinations: ['SN', 'CI'], origins: ['New York, NY', 'Newark, NJ', 'Paris, FR'], cargo: ['boxes', 'pallets', 'commercial'], rating: 4.6, reviews: 87, verified: true, responseHours: 1, onTime: 97, services: ['Cold chain', 'Pharma certified', 'Same-day pickup (NYC)'], about: 'Cold-chain air forwarder on the JFK–Dakar route. Every shipment travels with a temperature logger.', priceIndex: 3, plan: 'pro', initials: 'DD', hue: '#4ADE80' }),
  S({ id: 'monrovia-mail', name: 'Monrovia Mail & Cargo', tagline: 'Small parcels and barrels to Liberia', hq: 'Philadelphia, PA', founded: 2015, modes: ['ocean', 'air'], destinations: ['LR'], origins: ['Philadelphia, PA', 'Providence, RI', 'Minneapolis, MN'], cargo: ['barrels', 'boxes'], rating: 4.3, reviews: 96, verified: false, responseHours: 8, onTime: 88, services: ['Door pickup (Philadelphia)', 'Parcel consolidation'], about: 'Community forwarder serving the Liberian diaspora. Verification pending — licence documents submitted.', priceIndex: 1, plan: 'starter', initials: 'MM', hue: '#94A3B8' }),
  S({ id: 'rhine-africa', name: 'Rhine–Africa Container', tagline: 'German engineering cargo to the Gulf of Guinea', hq: 'Rotterdam, NL', founded: 2004, modes: ['ocean'], destinations: ['NG', 'GH', 'CI'], origins: ['Rotterdam, NL', 'Hamburg, DE'], cargo: ['container20', 'container40', 'commercial', 'vehicle'], rating: 4.7, reviews: 231, verified: true, responseHours: 4, onTime: 95, services: ['FCL', 'Project & out-of-gauge cargo', 'Machinery crating', 'Marine insurance'], about: 'Industrial forwarder for machinery, generators and construction equipment. Out-of-gauge specialists.', priceIndex: 3, plan: 'enterprise', initials: 'RA', hue: '#FCD34D' }),
  S({ id: 'sunrise-sea-air', name: 'Sunrise Sea & Air', tagline: 'Budget groupage every week from NY', hq: 'Newark, NJ', founded: 2017, modes: ['ocean', 'air'], destinations: ['GH', 'NG', 'TG'], origins: ['Newark, NJ', 'New York, NY', 'Philadelphia, PA'], cargo: ['barrels', 'boxes', 'pallets'], rating: 4.2, reviews: 318, verified: true, responseHours: 6, onTime: 87, services: ['Drop-off depot Newark', 'Door delivery Accra & Lagos'], about: 'Lowest per-barrel rates on the East Coast. Slower transit and busier customer service — but the price is hard to beat.', priceIndex: 1, plan: 'starter', initials: 'SS', hue: '#FDBA74' }),
  S({ id: 'takoradi-trade', name: 'Takoradi Trade Movers', tagline: 'Western Region Ghana, oil & gas supply chain', hq: 'Houston, TX', founded: 2011, modes: ['ocean', 'air'], destinations: ['GH'], origins: ['Houston, TX', 'Dubai, AE'], cargo: ['commercial', 'pallets', 'container20', 'container40'], rating: 4.8, reviews: 121, verified: true, responseHours: 1, onTime: 97, services: ['Oil & gas logistics', 'Dangerous goods certified', 'Bonded warehousing Takoradi', 'Customs brokerage'], about: 'Houston–Takoradi corridor for the energy industry. DG-certified staff and a bonded yard next to the port.', priceIndex: 3, plan: 'enterprise', initials: 'TT', hue: '#F43F5E' }),
  S({ id: 'westcoast-cargo-hub', name: 'WestCoast Cargo Hub', tagline: 'California to Ghana and Nigeria', hq: 'Los Angeles, CA', founded: 2013, modes: ['ocean', 'air'], destinations: ['GH', 'NG'], origins: ['Los Angeles, CA', 'Oakland, CA', 'Las Vegas, NV'], cargo: ['barrels', 'boxes', 'vehicle', 'container40', 'pallets'], rating: 4.5, reviews: 167, verified: true, responseHours: 3, onTime: 92, services: ['Door pickup (SoCal)', 'Vehicle shipping via Long Beach', 'Customs brokerage'], about: 'The West Coast option: vehicles and containers via Long Beach through Panama, air from LAX twice weekly.', priceIndex: 2, plan: 'starter', initials: 'WC', hue: '#22D3EE' }),
  S({ id: 'sahara-sky', name: 'Sahara Sky Express', tagline: 'Europe to francophone Africa by air', hq: 'Paris, FR', founded: 2014, modes: ['air'], destinations: ['SN', 'CI', 'TG'], origins: ['Paris, FR', 'Rotterdam, NL', 'London, UK'], cargo: ['boxes', 'pallets', 'commercial'], rating: 4.6, reviews: 142, verified: true, responseHours: 2, onTime: 94, services: ['Charles de Gaulle daily uplift', 'Customs brokerage Dakar & Abidjan', 'E-commerce returns'], about: 'Air-only forwarder for e-commerce and retail stock into Dakar, Abidjan and Lomé.', priceIndex: 3, plan: 'starter', initials: 'SS', hue: '#818CF8' }),
  S({ id: 'palm-coast-shipping', name: 'Palm Coast Shipping', tagline: 'Family barrels to Ghana since 1998', hq: 'Providence, RI', founded: 1998, modes: ['ocean'], destinations: ['GH'], origins: ['Providence, RI', 'New York, NY'], cargo: ['barrels', 'boxes', 'vehicle'], rating: 4.9, reviews: 634, verified: true, responseHours: 2, onTime: 97, services: ['Door pickup (New England)', 'Door delivery nationwide Ghana', 'Barrel supply', 'Duty estimates'], about: 'The longest-running Ghana forwarder in New England. Three generations, and the same clearance agent in Tema for twenty years.', priceIndex: 2, plan: 'enterprise', initials: 'PC', hue: '#E3B54A' }),
  S({ id: 'niger-delta-freight', name: 'Niger Delta Freight', tagline: 'Port Harcourt and Onne, not just Lagos', hq: 'Houston, TX', founded: 2012, modes: ['ocean'], destinations: ['NG'], origins: ['Houston, TX', 'Atlanta, GA'], cargo: ['vehicle', 'container20', 'container40', 'commercial', 'barrels'], rating: 4.5, reviews: 118, verified: true, responseHours: 4, onTime: 91, services: ['Onne port clearance', 'Vehicle shipping', 'FCL', 'Oil & gas supply'], about: 'Serves the South-South: Onne and Port Harcourt clearance so cargo for Rivers, Bayelsa and Akwa Ibom skips the Lagos road.', priceIndex: 2, plan: 'starter', initials: 'ND', hue: '#A3E635' }),
  S({ id: 'atlantic-swift-air', name: 'Atlantic Swift Air', tagline: 'US to Lagos & Accra in 72 hours', hq: 'New York, NY', founded: 2016, modes: ['air'], destinations: ['NG', 'GH'], origins: ['New York, NY', 'Newark, NJ', 'Houston, TX', 'Atlanta, GA'], cargo: ['boxes', 'pallets', 'commercial'], rating: 4.7, reviews: 276, verified: true, responseHours: 1, onTime: 96, services: ['Same-day pickup (NYC)', 'Airport-to-door', 'Customs pre-clearance', 'Insurance'], about: 'High-frequency air consolidations on the JFK–Lagos and JFK–Accra routes. Three departures a week.', priceIndex: 3, plan: 'pro', initials: 'AS', hue: '#38BDF8' }),
  S({ id: 'euro-africa-roro', name: 'Euro-Africa RoRo', tagline: 'Vehicles from Antwerp and Hamburg, weekly', hq: 'Hamburg, DE', founded: 2003, modes: ['ocean'], destinations: ['GH', 'NG', 'TG', 'CI', 'SN'], origins: ['Hamburg, DE', 'Rotterdam, NL'], cargo: ['vehicle', 'commercial'], rating: 4.6, reviews: 388, verified: true, responseHours: 5, onTime: 93, services: ['RoRo vehicles', 'Trucks & buses', 'Export customs EU'], about: 'Vehicle-only forwarder with weekly RoRo departures from Antwerp and Hamburg to five West African ports.', priceIndex: 2, plan: 'pro', initials: 'ER', hue: '#F59E0B' }),
  S({ id: 'gambia-gateway', name: 'Gambia Gateway Cargo', tagline: 'Senegambia groupage from London', hq: 'London, UK', founded: 2010, modes: ['ocean', 'air'], destinations: ['SN'], origins: ['London, UK', 'Manchester, UK'], cargo: ['barrels', 'boxes', 'pallets', 'vehicle'], rating: 4.4, reviews: 109, verified: false, responseHours: 7, onTime: 89, services: ['Door pickup (London)', 'Door delivery Dakar'], about: 'Serves Senegal and the Gambia from our Peckham depot. Verification in progress.', priceIndex: 1, plan: 'starter', initials: 'GG', hue: '#FB923C' }),
]
